### ISSUE TITLE
[BUG]: Signing test fails with 3 or more parties

### ISSUE THREAD

**Issue by matthiasgeihs** [silence-laboratories/silent-shard-dkls23-ll#48]
## Description

Signing test fails when running with 3 or more signers.

### Reproduce

In `src/dsg.rs`, add the following.

```rust
    #[test]
    fn sign_3_out_of_3() {
        let shares = dkg(3, 3);
        dsg(&shares[..3]);
    }
```

Run `cargo test --release dsg::tests::sign_3_out_of_3`.

This fails with:
```
---- dsg::tests::sign_3_out_of_3 stdout ----
thread 'dsg::tests::sign_3_out_of_3' panicked at src/dsg.rs:762:60:
called `Result::unwrap()` on an `Err` value: MissingMessage
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Expected Behavior

Should succeed.

## Environment

OS + Version: MacOS 14.6.1

Cargo Version: `cargo 1.81.0 (2dbb1af80 2024-08-20)`

HW type: aarch64 (This asks for the CPU architecture, right?)

**Comment by matthiasgeihs** [comment]
Ah, found the bug.

https://github.com/silence-laboratories/silent-shard-dkls23-ll/blob/181383a5f085fb6d9a5ecc7ebcf8c173fd71f7cf/src/dsg.rs#L759

This should be `.filter(|msg| msg.to_id == party.keyshare.party_id)`, right?

Same in line 773.

The first message doesn't have a `to` field, so this doesn't apply?

**Comment by Rhonstin** [comment]
## ♻️ Sprint Carryover #1

This issue was carried over from **{"sprint":"Sprint 5","done":true}** → **Sprint 5**.

> Total carryovers: **1**

**Comment by Rhonstin** [comment]
## ♻️ Sprint Carryover #2

This issue was carried over from **{"sprint":"Sprint 5","done":true}** → **Sprint 5**.

> Total carryovers: **2**
